name: GitHappens_FinalProject
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - contourpy=1.3.1
  - cycler=0.11.0
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - astroid==3.3.9
    - colorama==0.4.6
    - coverage==7.8.0
    - dill==0.4.0
    - iniconfig==2.1.0
    - isort==6.0.1
    - mccabe==0.7.0
    - platformdirs==4.3.7
    - pluggy==1.5.0
    - pylint==3.3.6
    - pytest==8.3.5
    - pytest-cov==6.1.1
    - seaborn==0.13.2
    - tomlkit==0.13.2
    - -e ./src/final_project_git_happens

